### ISSUE TITLE
A minor bug in preprocessing code

### ISSUE THREAD

**Issue by SuX97** [ZGCTroy/CamI2V#3]
Great work!

https://github.com/ZGCTroy/CamI2V/blob/main/datasets/utils/generate_dataset.py#L114
```
os.system(f"mv {tmpname} {filepath}")
```
will causing file not found exception, revise it to:
```
os.system(f"mv {os.path.join('/tmp', tmpname)} {filepath}")
```
will solve it!

**Comment by MuteApo** [comment]
Thanks for your attention! It has been fixed in a recent commit.
